version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: nerve_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  nerve-app:
    build: .
    container_name: nerve_app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017

volumes:
  mongo-data:
