version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: nerve_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  nerve-app:
    build: ./backend
    container_name: nerve_app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
    volumes:
      - ./backend/log:/app/log
      
  nerve-dashboard:
    build: ./frontend
    container_name: nerve_dashboard
    ports:
      - "8080:80"
    depends_on:
      - nerve-app

  mongo-express:
    image: mongo-express:1.0.2-20
    container_name: nerve_mongo_express
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    
volumes:
  mongo-data:
